[package]
name = "weeb_3"
version = "0.0.0"
edition = "2024"
description = "A Swarm client for browsers"
license = "MIT"
repository = "https://github.com/lat-murmeldjur/weeb-3"
homepage = "https://github.com/lat-murmeldjur/weeb-3#readme"

[[bin]]
name = "weebery"
path = "src/main.rs"

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
strip = "symbols"

[package.metadata.wasm-pack.profile.release]
wasm-opt = ["-O", "--all-features"]

[dependencies]
rand = "0.8"
prost = "0.14.4"
serde_json = "1"
event-listener = "5.4.1"
futures = "0.3.33"
bytes = "1.12"

[build-dependencies]
prost-build = "0.14.4"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
axum = { git = "https://github.com/tokio-rs/axum.git", default-features = false, features = ["original-uri"] }
axum-server = { git = "https://github.com/programatik29/axum-server.git", features = ["tls-rustls-no-provider"] }
rustls = { version = "0.23", default-features = false, features = ["ring", "std", "tls12"] }
rust-embed = { version = "8.7.1", features = ["compression", "include-exclude", "interpolate-folder-path"] }
tokio = { version = "1.38.0", default-features = false, features = ["macros", "net", "rt"] }
tower-http = { git = "https://github.com/tower-rs/tower-http.git", features = ["cors"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
alloy-primitives = { git = "https://github.com/alloy-rs/core.git", default-features = false, features = ["std", "k256"] }
k256 = { version = "0.13.4", default-features = false, features = ["ecdsa", "std"] }
async-std = { git = "https://github.com/async-rs/async-std.git" }
libp2p = { git = "https://github.com/libp2p/rust-libp2p.git", rev = "6348a0be4aeb5b48eecf17a5d0aae15ff8239984", features = [
    "ecdsa",
    "identify",
    "macros",
    "noise",
    "ping",
    "websocket-websys",
    "yamux",
] }
libp2p-stream = { git = "https://github.com/libp2p/rust-libp2p.git", rev = "6348a0be4aeb5b48eecf17a5d0aae15ff8239984" }
wasm-bindgen = "0.2.100"
wasm-bindgen-futures = "0.4.50"
js-sys = { version = "0.3.77" }
web-sys = { version = "0.3.77", features = [
  'console',
  'Blob',
  'BlobPropertyBag',
  'Document',
  'DocumentFragment',
  'Element',
  'Event',
  'EventTarget',
  'File',
  'FileList',
  'FilePropertyBag',
  'History',
  'HtmlButtonElement',
  'HtmlElement',
  'HtmlInputElement',
  'HtmlMediaElement',
  'HtmlSpanElement',
  'HtmlSelectElement',
  'Location',
  'MediaQueryList',
  'MessagePort',
  'MessageChannel',
  'Navigator',
  'Node',
  'ServiceWorker',
  'ServiceWorkerContainer',
  'ServiceWorkerRegistration',
  'SharedWorker',
  'WorkerOptions',
  'WorkerType',
  'RegistrationOptions',
  'TimeRanges',
  'Url',
  'UrlSearchParams',
  'Window',
] }
hex = "0.4.3"
web3 = { git = "https://github.com/tomusdrw/rust-web3.git", default-features = false, features = ["eip-1193", "http"] }
tar = { git = "https://github.com/alexcrichton/tar-rs.git" }
mime_guess = { git = "https://github.com/abonander/mime_guess.git", default-features = false }
indexed_db_futures = { git = "https://github.com/Alorel/rust-indexed-db.git" }
base64 = "0.22.1"
async-lock = "3.4.2"

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-bindgen-test = "0.3.50"

[dev-dependencies]
async-std = { git = "https://github.com/async-rs/async-std.git" }
async-lock = "3.4.2"
headless_chrome = "1.0.21"
sysinfo = { version = "0.39.6", default-features = false, features = ["system"] }
anyhow_crates_io = { package = "anyhow", version = "1" }
serde = { version = "1.0.219", features = ["derive"] }
sha3_crates_io = { package = "sha3", version = "0.10.9" }
